net: ieee802154: adf7242: Fix bug if defined DEBUG
This fixes undefined reference to struct adf7242_local *lp in
case DEBUG is defined.

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>